---
##################################
##################################
## Google Format GitHub Actions ##
##################################
##################################
name: Google Java Formatter

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#################
# Start the job #
#################
on:
  # Pull request into the master or main branch
  pull_request:
    branches: [ master, main ]
  # release is created
  release:
    types: [ created ]


###############
# Set the Job #
###############
jobs:
  formatting:
    # Name the Job
    name: Formatting
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      - if: github.event_name != 'pull_request'
        uses: actions/checkout@v2
      - if: github.event_name == 'pull_request'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-java@v2
        with:
          java-version: 17
      - uses: axel-op/googlejavaformat-action@3.5.0
        with:
          args: "--skip-removing-unused-imports --skip-reflowing-long-strings --skip-javadoc-formatting --replace"
          #commitMessage: "Google Java Formatter"
          #files: "**/main/java/com.webcheckers/@(application|model|ui)/*.java"