---
##################################
##################################
## Google Format GitHub Actions ##
##################################
##################################
name: Java Google Format

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#################
# Start the job #
#################
on:
  # Pull request into the master or main branch
  pull_request:
    branches: [master, main]
  # release is created
  release:
    types: [created]


###############
# Set the Job #
###############
jobs:
  formatting:
    # Name the Job
    name: Google Java Formatter
    # Set the agent to run on
    runs-on: ubuntu-latest
    
    ##################
    # Load all steps #
    ##################
    steps:
      ###################################
      # Run formatter against code base #
      ###################################
      - uses: actions/checkout@v2
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-removing-unused-imports --replace"
          commitMessage: "Google Java Formatter"
